#Server
server:
  port: 8500
  servlet:
    context-path: /
    encoding:
      charset: UTF-8

#DataBase
spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://gettersettersitter.cocxfarlqxip.ap-northeast-2.rds.amazonaws.com:3306/GetterSetterSitter?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: admin
    password: gst12345
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: false
  freemarker:
    cache: false
  jackson:
    serialization:
      fail-on-empty-beans: false


  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        default_batch_fetch_size: 100
        naming:
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl


  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: 32c824e36d69a48d965a21ec5f8f90f4
            redirect-uri: http://localhost:8500/member/login
            authorization-grant-type: authorization_code
            client-authentication-method: POST
            client-name: Kakao
            scope:
              - profile_nickname
              - account_email
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

  servlet:
    multipart:
      enabled: true
      location: C:\uploadfile\
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB

#resource:
#  handler: notice/detail/**
#  location: file:///C:/uploadfile/


#logging:
#  level:
#    org.springframework.web: DEBUG
#    com.pet.sitter: INFO





